---

- hosts: all
  become: true
  tasks:
#  sudp apt update
  - name: update repository index
    apt:
      update_cache: yes

# sudo apt install apach2
  - name: install apache2 package
    apt:
      name: apache2
      state: latest # absent to remove the package <=> sudo apt remove apache2
  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
