---

- hosts: all
  become: true
  tasks:
#  sudp apt update
  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"] 

# sudo apt install apach2
  - name: install apache2 package
    apt:
      name: apache2
      state: latest # absent to remove the package <=> sudo apt remove apache2
    when: ansible_distribution == "Ubuntu" 
    
  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu" 
